---
language: python
python: "2.7"

sudo: required

before_install:
  - pwd
  - "sudo apt-get -y install curl lsb_release || true"
  - curl https://storage.googleapis.com/git-repo-downloads/repo > /tmp/repo
  - chmod a+x /tmp/repo
  - sudo mv /tmp/repo /bin/repo
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - "[ -d /opt/chaperone ] || sudo mkdir -p /opt/chaperone"
  - export SLUG=$TRAVIS_REPO_SLUG
  - export BRANCH=$TRAVIS_BRANCH
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export SLUG=$TRAVIS_PULL_REQUEST_SLUG; export BRANCH=$TRAVIS_PULL_REQUEST_BRANCH; fi'

  # get the username portion from github
  - export GIT_USER=${SLUG%/*}
  - export CHAPERONE_BRANCH="master"
  - git ls-remote --exit-code --heads https://github.com/$GIT_USER/chaperone "$BRANCH" && CHAPERONE_BRANCH=$BRANCH || true
  - env

install:
  - pip install ansible ansible-lint

script:
  - cd /tmp
  - echo "y" | repo init -u https://github.com/$GIT_USER/chaperone -b $CHAPERONE_BRANCH -g chaperone
  - repo sync
  - cd ansible/playbooks/ansible
  - ansible-playbook -i inventory ansible.yml
