---

# send ssh keys and get the photon hosts ready
- name: distribute ssh keys to the new vms
  include: sshkeys.yml

- name: Prepare VMs
#  gather_facts: false
  hosts: photon
  roles:
    - photon
    - pip
    - liota
  tasks:

    - name: Open Mosquitto ports
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: "{{ item }}"
        jump: ACCEPT
      with_items:
        - 80
        - 1883
        - 2003
        - 2004
        - 7002
        - 9001
      tags: ["docker"]

    - name: Run Mosquitto service
      docker_container:
        name: mosquitto
        image: toke/mosquitto
        state: started
        published_ports:
          - 1883:1883
          - 9001:9001
      run_once: true
      tags: ["docker"]

    - name: Run Graphite service
      docker_container:
        name: graphite
        image: nickstenning/graphite
        state: started
        published_ports:
          - 80:80
          - 2003:2003
          - 2004:2004
          - 7002:7002
      run_once: true
      tags: ["docker"]