---

# send ssh keys and get the photon hosts ready
- name: distribute ssh keys to the new vms
  include: sshkeys.yml

- name: Prepare VMs
#  gather_facts: false
  hosts: photon
  roles:
    - photon
    - pip


